export const RECEIVE_STATES = 'RECEIVE_STATES';
export const SET_SELECT_RECORD_TYPE = 'SET_SELECT_RECORD_TYPE';
export const RECEIVE_RECORD_LIST = 'RECEIVE_RECORD_LIST';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
